apiVersion: v1
kind: Pod
metadata:
  name: app1114
  labels:
    name: test
spec:
  containers:
  - name: testapp
    image: samuel3wang/app1114:0.0.1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3000

